### ISSUE TITLE
System.TypeInitilizationException thrown

### ISSUE THREAD

**Issue by darda1** [deniszykov/commandline#7]
I am using last version, 1.3.2.

When I use the app without parameters, the defaultCommandName is being invoked without a problem. If I put any command there, it works fine (all have optional arguments).

But when I use any command, i get this:

System.TypeInitializationException: The type initializer for 'System.TypeConvert' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'TypeConversion`2' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'ConvertibleType`1' threw an exception.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Linq.EmptyPartition`1[System.TypeConvert+ConvertMethodInfo]' to type 'ConvertMethodInfo[]'.
   at System.TypeConvert.ConvertibleType`1..cctor()
   --- End of inner exception stack trace ---
   at System.TypeConvert.ConvertibleType`1.TryFindToConversion(Type toType, ConvertMethodInfo& convertMethod)
   at System.TypeConvert.TypeConversion`2..cctor()
   --- End of inner exception stack trace ---
   at System.TypeConvert.RegisterCustomConversion[FromType,ToType](Func`4 convertFunc)
   at System.TypeConvert.InitializeNativeConversions()
   at System.TypeConvert..cctor()
   --- End of inner exception stack trace ---
   at System.TypeConvert.ToString(Object value, String format, IFormatProvider formatProvider)
   at System.CommandLine.BindMethod(Type type, String defaultMethodName, CommandLineArguments arguments)
   at System.CommandLine.Run(Type type, CommandLineArguments arguments, String defaultCommandName)

**Comment by deniszykov** [comment]
Hi @darda1! Thanks for reporting this bug. It is .NET Core 3.0 change regarding `Enumerable.Empty<T>` is not Array type anymore. I will fix it soon.

**Comment by deniszykov** [comment]
fixed in version 1.3.3
